### PR TITLE
Addition to the Projects List: Lumos

### PR DESCRIPTION
**Pull request by jonathanrjpereira**
Lumos

 mimics the natural light of the sun as it passes overhead each day, generating bright blue light in the morning and warmer amber light in the evening in order to trigger the production of hormones like cortisol & melatonin which improves the user's sleep.

# Please make sure all below checkboxes have been checked before submitting your PR.

- [x] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [x ] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
	- [x] includes a valid (https) link,
	- [x] includes a concise and on-topic description,
	- [x] mentions if there is only support some devices,
	- [x] is not a duplicate,
	- [x] has been added at the bottom of the appropriate category,
	- [x] is in the form of **Named Link - Description, seperated by commas.**
	- [x] ends with a dot.

### CODE REVIEW

**Comment by thibmaek** [comment]
Thanks for the addition! This looks like a project I can't wait to try myself.

Before this gets merged, one small thing I want to make sure off: you added the supports Rpi 3 badge to the item. Adding this badge means that this project can only be built/made/used on a Raspberry Pi 3 or higher (due to its CPU architecture). Could you confirm this is the case? (your article mentions Raspberry Pi Zero, there is also a badge for that)

**Comment by jonathanrjpereira** [comment]
RasPi zero too. It uses the Bluetooth Radio of a RasPi & hence isn't compatible with the RasPi 2

**Comment by thibmaek** [comment]
@jonathanrjpereira thanks for the fast reply! Could you add the Raspberry Pi Zero badge as well (after the other badge)? I'll happily merge yet another great contribution then. ✨

**Comment by jonathanrjpereira** [comment]
Just added the Raspberry Pi zero badge too

**Pull request merged**
