### PR TITLE
Added TelepI

### PR DESCRIPTION
**Pull request by besoeasy**
# Please make sure all below checkboxes have been checked before submitting your PR.

- [x] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [x] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
  - [x] includes a valid (https) link,
  - [x] includes a concise and on-topic description,
  - [x] mentions if there is only support some devices,
  - [x] is not a duplicate,
  - [x] has been in the correct alphabetical order for its section,
  - [x] is in the form of **Named Link - Description, separated by commas.**
  - [x] ends with a dot.

### CODE REVIEW

**Comment by thibmaek** [comment]
Can you make sure the summary is one concrete sentence? Other than that it's good to go.

BTW I checked the install script, you don't need to prefix commands with `sudo` when you perform this check 😉 :

```bash
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root or with sudo."
    exit 1
fi
```

**Review by thibmaek — CHANGES_REQUESTED** [review]
Make sure it's one concrete sentence instead of two

**Comment by besoeasy** [comment]
> Make sure it's one concrete sentence instead of two

yea, my bad for overlooking that

**Review by thibmaek — APPROVED** [review]

**Comment by thibmaek** [comment]
🤝 Thanks for contributing this resource!

**Pull request merged**
