### PR TITLE
Add Cloud Fetch

### PR DESCRIPTION
**Pull request by besoeasy**
# Please make sure all below checkboxes have been checked before submitting your PR.

- [x] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [x] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
  - [x] includes a valid (https) link,
  - [x] includes a concise and on-topic description,
  - [x] mentions if there is only support some devices,
  - [x] is not a duplicate,
  - [x] has been in the correct alphabetical order for its section,
  - [x] is in the form of **Named Link - Description, separated by commas.**
  - [x] ends with a dot.

### CODE REVIEW

**Comment by besoeasy** [comment]
@thibmaek

**Comment by thibmaek** [comment]
Don't see how this is a Raspberry Pi specific thing?

**Comment by besoeasy** [comment]
> Don't see how this is a Raspberry Pi specific thing?

Its for turning raspberry pi for on the fly download manager

the other linux and pc implementations are manual and requires spcl software packages to be installed(But since development version has to run on pc for developers to build and test), whereas raspberry pi install is pure headless, in future adding support for screen hat to show live status about downloads on display.

**Comment by besoeasy** [comment]
@thibmaek

**Comment by thibmaek** [comment]
Still don't see how this leverages the Raspberry Pi specifically. It's a piece of software that can run on any machine but just has an easier install script on Raspberry Pi?

**Pull request closed without merging**
