### PR TITLE
:heavy-plus-sign: Added list of useful android apps

### PR DESCRIPTION
**Pull request by anshulahuja98**
I have personally used these apps and found them very useful for ease of use with Pi.

- [x] I have read and understood the [contribution guidelines](https://github.com/thibmaek/awesome-raspberrypi/blob/master/CONTRIBUTING.md).
- [x] This pull request has a descriptive title. *(For example: `Add Raspbian`)*
- The topic I added
	- [x] includes a valid (https) link,
	- [x] includes a concise and on-topic description,
	- [x] mentions if there is only support some devices,
	- [x] is not a duplicate,
	- [x] has been added at the bottom of the appropriate category,
	- [x] is in the form of **Named Link - Description, seperated by commas.**
	- [x] ends with a dot.

### CODE REVIEW

**Comment by anshulahuja98** [comment]
Travis is not failing due to my links, please look into it

**Comment by thibmaek** [comment]
Indeed, those changes are related to me not updating my links since I changed my domain name 😅 will fix that. 

Other than that, I think adding this is a good idea but I would generalize it and just make it apps instead of Android apps.

**Comment by anshulahuja98** [comment]
I have changed it to Apps

**Comment by thibmaek** [comment]
Cool, could you also format the links like this:

```markdown
[Termius] -  One of the cleanest SSH Client for Pi. [Android](https://play.google.com/store/apps/details?id=com.server.auditor.ssh.client)
```

That way people can include iOS links as well.
PS: There's a typo in Terminus, it's Termius ;)

Thanks for adding this, really good idea!

**Comment by anshulahuja98** [comment]
I have updated the links and fixed the typo
I have put the app names in bold.

**Comment by thibmaek** [comment]
Good, I just went ahead and moved them to the correct parent section.
PR looks good, thanks :)

**Comment by anshulahuja98** [comment]
Thanks for merging, i'll update soon with some more apps, and a project of mine

**Pull request merged**
